// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLwfcg42p6cJ93F_fEeCNusXU_k4bx7Gk',
    appId: '1:1034878959108:web:eb1ff2500ca82fa088ff51',
    messagingSenderId: '1034878959108',
    projectId: 'three-bits',
    authDomain: 'three-bits.firebaseapp.com',
    storageBucket: 'three-bits.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM8WMoxJgTsFU_HavOqD3iqqHUj8FseVY',
    appId: '1:1034878959108:android:69a753494fe59a5188ff51',
    messagingSenderId: '1034878959108',
    projectId: 'three-bits',
    storageBucket: 'three-bits.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2758TJCeu7Nfr8Q8-RqgBu29T59qu3rQ',
    appId: '1:1034878959108:ios:76e38c1a85f5b86688ff51',
    messagingSenderId: '1034878959108',
    projectId: 'three-bits',
    storageBucket: 'three-bits.firebasestorage.app',
    iosBundleId: 'com.11b.boxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2758TJCeu7Nfr8Q8-RqgBu29T59qu3rQ',
    appId: '1:1034878959108:ios:7f73c13eacf8305a88ff51',
    messagingSenderId: '1034878959108',
    projectId: 'three-bits',
    storageBucket: 'three-bits.firebasestorage.app',
    iosBundleId: 'com.u11b.boxApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLwfcg42p6cJ93F_fEeCNusXU_k4bx7Gk',
    appId: '1:1034878959108:web:b82f64205c13f71788ff51',
    messagingSenderId: '1034878959108',
    projectId: 'three-bits',
    authDomain: 'three-bits.firebaseapp.com',
    storageBucket: 'three-bits.firebasestorage.app',
  );
}
